### ISSUE TITLE
Construction of Unit of Work Slow

### ISSUE THREAD

**Issue by 0l0r1n** [ImJohnMDaniel/at4dx#29]
We are trying to create an unit of work using the AT4DX framework with caching enabled and we noticed that it takes about 2.5 seconds to generate a new UoW.

Org details:
- Number of sObjects: 198
- Number of bindings for Unit of work: 12
- Steps to reproduce:

```apex
System.debug('Start : ' + Limits.getCpuTime());
IApplicationSObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
System.debug('Stop : ' + Limits.getCpuTime());
```

**Comment by ImJohnMDaniel** [comment]
Issue is fixed by PR #30
